apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - backend.yaml
  - mysql.yaml

images:
  - name: jenkins-argo-demo
    newName: 192.168.142.101:30500/jenkins-argo-demo
    newTag: b12
  - name: jenkins-argo-backend
    newName: 192.168.142.101:30500/jenkins-argo-backend
    newTag: b12
