apiVersion: v1
kind: Service
metadata:
  name: demo-web
  namespace: cicd-demo
spec:
  type: LoadBalancer
  selector:
    app: demo-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
